/* 7zVersion.h */

#ifndef __7Z_VERSION_H
#define __7Z_VERSION_H

#define MY_VERSION_MAJOR 21
#define MY_VERSION_MINOR 7
#define MY_VERSION_BUILD 0
#define MY_VERSION_BUG 0

#define MY_VERSION_NUMBERS "21.07"
#define MY_VERSION MY_VERSION_NUMBERS

#define MY_DATE "2021-12-26"
#define MY_COPYRIGHT "Copyright (c) 2021 Igor Pavlov"
#define MY_VERSION_COPYRIGHT_DATE MY_VERSION " : " MY_COPYRIGHT " : " MY_DATE

#define MY_7ZIP_VERSION "21.07"
#define MY_7ZIP_VERSION_TRUNCATED "21.07"
#define P7ZIP_VERSION "21.07 ZS"

#define MY_7Z_FILE_VERSION_MAJOR MY_VERSION_MAJOR
#define MY_7Z_FILE_VERSION_MINOR MY_VERSION_MINOR

#define MY_IMPLEMENTATION_NAME "LZMA"
#define MY_IMPLEMENTATION_VERSION "21.07"
#define MY_IMPLEMENTATION_VERSION_CPU MY_IMPLEMENTATION_VERSION

#define MY_CPU_POSTFIX_DEF ""
#define MY_CPU_POSTFIX ""
#define MY_COPYRIGHT_POS_2 24

#endif /* __7Z_VERSION_H */